#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Meshing
blockMesh
surfaceFeatures
snappyHexMesh -overwrite

# Create the inlet/outlet and AMI patches
runApplication createBaffles -overwrite
runApplication splitBaffles -overwrite

# Renumbering
runApplication renumberMesh -noFields -overwrite

#------------------------------------------------------------------------------
